#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManagement:
    transition: FadeTransition()
    HomeScreen:
    AdvancedScreen:
    
<LabelwColor@Label>:
    bcolor: 0.1,0,0,1
    canvas.before:
        Color:
            rgba: self.bcolor
        Rectangle:
            pos: self.pos
            size: self.size

    
<StationLabel@LabelwColor>:
    markup: True
    font_size: 24
    size_hint: (0.5,1)
    bcolor: 0.3,0.3,0.3,0.4
    
<StationInfo@LabelwColor>:
    markup: True
    font_size: 20
    halign: 'center'

<HomeScreen>:
    name: "Home"
    Image: 
        source: 'D:/Backup/SUTD/Introduction to Digital World/1D Anti-hogging/SeatApp/staircase.jpg'
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        allow_stretch: True
        
    BoxLayout:
        spacing: 5
        padding: 10
        orientation: 'vertical'
        
        LabelwColor: 
            text: '[i]Py Lab Station Occupancy[/i]'
            markup: True
            bcolor: 0.3,0.3,0.3,0.4
            font_size: 30
            size_hint: (1,0.6)
            
        GridLayout:
            spacing: 5
            padding: 10
            cols: 2
        
            StationLabel:
                id: station_1
                text: '[i]Station 1[/i]'
                 
            StationInfo:
                text: root.stations.stationDict['station_1'] 
                bcolor: root.colorscheme(self.text)
                           
            StationLabel:
                id: station_2
                text: '[i]Station 2[/i]'
                 
            StationInfo:
                text: root.stations.stationDict['station_2']
                bcolor: root.colorscheme(self.text)
                
                
            StationLabel:
                id: station_3
                text: '[i]Station 3[/i]'
                 
            StationInfo:
                text: root.stations.stationDict['station_3']
                bcolor: root.colorscheme(self.text)
                         
        LabelwColor:
            text: '[i]Last Refresh Time[/i] : ' + root.stations.refreshTime
            markup: True
            font_size: 22
            bcolor: 0.3,0.3,0.3,0.4
            size_hint: (1,0.3)         
            
        GridLayout:
            spacing: 5
            padding: 10
            cols: 2
            size_hint: (1,0.6)
            
            Button:
                text: '[i]Refresh Page[/i]'
                markup: True
                font_size: 30
                background_color: [0.5,0.5,0.5,0.5]
                on_release: root.stations.refresh()
                
            Button:
                text: '[i]Advanced[/i]'
                markup: True
                font_size: 30
                background_color: [0.5,0.5,0.5,0.5]
                on_release: app.root.current = 'Advanced'
                
<AdvancedScreen>:
    name: "Advanced"
    
    Label:
        text: root.stations.serverInstance.allData
        
    Button:
        text: '[i]List All Data From Firebase[/i]'
        markup: True
        font_size: 30
        size_hint: (1,0.4)
        background_color: [0.5,0.5,0.5,0.5]
        on_release: root.stations.serverInstance.listAllFirebaseData()
        
    FloatLayout:
        Button:
            color: 0,1,0,1
            font_size: 25
            size_hint: 0.3,0.2
            text: "Back"
            on_release: app.root.current = 'Home'
            pos_hint: {'right':1 , 'top':1}